### ISSUE TITLE
Suggestion: Fix repo size

### ISSUE THREAD

**Issue by abdulfatir** [johannbrehmer/manifold-flow#4]
The current size of the repo is ~400 MB. I think it would be a good idea to either quash commits or create a separate public branch which isn't bloated. 

Thanks a lot for releasing the code. :)

**Comment by johannbrehmer** [comment]
Hi,

Thank you for the suggestion! I've opened a new branch  [`public`](https://github.com/johannbrehmer/manifold-flow/tree/public) with the same code but none of the commit history.

Later I may be able to clean up the history of `master` some more, but that may take some time -- closing this for now.

Cheers,
Johann
